FROM rust:1.61.0 as builder
WORKDIR /usr/src/slowpoke-telegram
ARG SLOWPOKE_SOURCE_URL=https://github.com/ZaMaZaN4iK/slowpoke-telegram.git
ARG CACHE_DATE=2020-01-01
RUN git clone --single-branch --branch main ${SLOWPOKE_SOURCE_URL}
WORKDIR slowpoke-telegram
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates && apt-get clean
COPY --from=builder /usr/local/cargo/bin/slowpoke-telegram /usr/local/bin/slowpoke-telegram
CMD ["slowpoke-telegram"]
