FROM fedora:latest

LABEL maintainer="Alexander Zaitsev <zamazan4ik@tut.by>"

ARG SLOWPOKE_VERSION=1.0.0

ARG SLOWPOKE_SOURCE_URL=https://github.com/ZaMaZaN4iK/slowpoke-telegram/archive/v${SLOWPOKE_VERSION}.zip

RUN dnf install -y openssl ca-certificates wget unzip

WORKDIR /usr/src/slowpoke-telegram

RUN wget ${SLOWPOKE_SOURCE_URL} && unzip v${CODEDETECTION_VERSION}.zip

WORKDIR codedetection-telegram-${SLOWPOKE_VERSION}

RUN CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --target install && \
    rm -rf /usr/src/slowpoke-telegram

WORKDIR /usr/local/bin

ENTRYPOINT ["/usr/local/bin/slowpoke_telegram"]

