FROM rust:1.44 as builder
WORKDIR /usr/src/slowpoke-telegram
ARG SLOWPOKE_SOURCE_URL=https://github.com/ZaMaZaN4iK/slowpoke-telegram.git
RUN git clone ${SLOWPOKE_SOURCE_URL}
WORKDIR slowpoke-telegram
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates
COPY --from=builder /usr/local/cargo/bin/slowpoke-telegram /usr/local/bin/slowpoke-telegram
CMD ["slowpoke-telegram"]
