FROM rust:1.49.0 as builder
WORKDIR /usr/src/slowpoke-telegram
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates && aplt-get clean
COPY --from=builder /usr/local/cargo/bin/slowpoke-telegram /usr/local/bin/slowpoke-telegram
CMD ["slowpoke-telegram"]
